apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-mezzache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: wmezz/backend-app:v6
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service-mezzache
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: mydatabase

