apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-mezzache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: wmezz/frontend-app:v7
        ports:
        - containerPort: 80
