apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydatabase;
    USE mydatabase;

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255),
        email VARCHAR(255)
    );

    INSERT INTO users (name, email) VALUES
        ('John', 'john@example.com'),
        ('Emma', 'emma@example.com'),
        ('Michael', 'michael@example.com');
