name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login and AKS Set Context
        run: |
          az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      - name: Build Docker image
        run: |
          docker build -t wmezz/backend-app .
          docker login -u wmezz -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag wmezz/backend-app wmezz/backend-app:v3
          docker push wmezz/backend-app:v3
          docker-compose up -d

      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f mysql-deployment.yaml
          kubectl apply -f mysql-service.yaml
          kubectl apply -f mysql-pv.yaml
          kubectl apply -f mysql-pvc.yaml


          

