name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v2
        with:
          az-version: latest

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Azure Login and AKS Set Context
        run: |
          az login 
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      - name: Build Docker image
        run: |
          docker build -t wmezz/backend-app .
          docker login -u wmezz -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wmezz/backend-app

      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

